# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghproj < Formula
  desc "Add GitHub Issues and Pull Requests to GitHub Projects
"
  homepage "https://github.com/suzuki-shunsuke/ghproj"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.5/ghproj_darwin_amd64.tar.gz"
      sha256 "f8c45363baa3f010ceac4715f4d80d27ea443c1e6f07ab91a22e04e23c5bbaed"

      def install
        bin.install "ghproj"
        generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.5/ghproj_darwin_arm64.tar.gz"
      sha256 "78c8b2abc416306173e6148e0bcf58689bde4d53bd88929562d65d6b0b476386"

      def install
        bin.install "ghproj"
        generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.5/ghproj_linux_amd64.tar.gz"
        sha256 "01a0d8cf2fe10835661416288a9a7b1a3156f7e256fd844b9d0c77d8cf2bf537"

        def install
          bin.install "ghproj"
          generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.5/ghproj_linux_arm64.tar.gz"
        sha256 "cdde6e96d2f107caf8e9cf9002175769d79e1cdc8dabce16a3b97df2c58286d0"

        def install
          bin.install "ghproj"
          generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghproj --version"
  end
end
