# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghproj < Formula
  desc "Add GitHub Issues and Pull Requests to GitHub Projects
"
  homepage "https://github.com/suzuki-shunsuke/ghproj"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.6/ghproj_darwin_amd64.tar.gz"
      sha256 "b12e28bc1dca8bc04b210fbb9cfeef84017314e1ea072da33aa6cffe962b02c1"

      def install
        bin.install "ghproj"
        generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.6/ghproj_darwin_arm64.tar.gz"
      sha256 "89b14f3b6d0a3320c9fce2c3a2d0bddb35588c1edc51aff43fe1e4b870108c51"

      def install
        bin.install "ghproj"
        generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.6/ghproj_linux_amd64.tar.gz"
        sha256 "ecb0e4e48e4355c2cbfc305beb1ed349094fb6f8fb01de504aeaac05d8d5afee"

        def install
          bin.install "ghproj"
          generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.6/ghproj_linux_arm64.tar.gz"
        sha256 "16b5533782f70ff5330ec3775a36679247cb1d8247d54fd1e5666f459f4cab73"

        def install
          bin.install "ghproj"
          generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghproj --version"
  end
end
