# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghproj < Formula
  desc "Add GitHub Issues and Pull Requests to GitHub Projects
"
  homepage "https://github.com/suzuki-shunsuke/ghproj"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.3/ghproj_darwin_amd64.tar.gz"
      sha256 "572f2cb0d5497e47f82114a81545a70127410a94e88205a61136e2a593f28bca"

      def install
        bin.install "ghproj"
        generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.3/ghproj_darwin_arm64.tar.gz"
      sha256 "a5efcf48f5a3c43070db6e7a26366d75b6567d05765439eefa3ab2a501fb4cc2"

      def install
        bin.install "ghproj"
        generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.3/ghproj_linux_amd64.tar.gz"
        sha256 "3be9680350a85e26891af30e4bcc8d3879e12d1d079471b566b696c55c67b517"

        def install
          bin.install "ghproj"
          generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.3/ghproj_linux_arm64.tar.gz"
        sha256 "9543d78aacd77f64495a11bfb5f1fa28a41bfc84f6ed0f4527d12fd6cfdfcf3d"

        def install
          bin.install "ghproj"
          generate_completions_from_executable(bin/"ghproj", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghproj --version"
  end
end
