# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghproj" do
  desc "Add GitHub Issues and Pull Requests to GitHub Projects
"
  homepage "https://github.com/suzuki-shunsuke/ghproj"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghproj"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.7/ghproj_darwin_amd64.tar.gz"
      sha256 "dcb61f362428813d19bab917d9899a036b1097648a21b5469bb749a0abceeb88"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.7/ghproj_darwin_arm64.tar.gz"
      sha256 "942f021577db41300eb261495f4f955e0e9f25f74e3717417dca8fe8f9453eb6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.7/ghproj_linux_amd64.tar.gz"
      sha256 "206eb302ed2c46be1847dcf061a4b97634900455951c8d78349b27feeedaed4a"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.7/ghproj_linux_arm64.tar.gz"
      sha256 "c2be46204c240a8578055a396af2875a909006391b9521310a67a6dab16946f9"
    end
  end

  # No zap stanza required
end
