# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghproj" do
  desc "Add GitHub Issues and Pull Requests to GitHub Projects
"
  homepage "https://github.com/suzuki-shunsuke/ghproj"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghproj"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.9/ghproj_darwin_amd64.tar.gz"
      sha256 "7a655ab092b15bcc197b529acd19f10669021fd27a4f695a48a2e1a8578de644"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.9/ghproj_darwin_arm64.tar.gz"
      sha256 "2d85a5bec984ed9ff8be309b352f469d38984faa0d3729b4d85897dc22c239a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.9/ghproj_linux_amd64.tar.gz"
      sha256 "81fcbaec7c64df8a008ed16bfd94438cfdc916916e27ee3048a81c0147d9d831"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghproj/releases/download/v0.1.9/ghproj_linux_arm64.tar.gz"
      sha256 "2982f56696a3dff1dcc4a07963dc2f7501ac1389664227940e9d6318ca6f32cf"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghproj"]
    end
  end

  # No zap stanza required
end
